name: 'sintr_ui'
version: 0.0.1
description: An absolute bare-bones web app.

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  _discoveryapis_commons: '>=0.1.0 <0.2.0'
  browser: '>=0.10.0 <0.11.0'
  codemirror: '>=0.2.8 <0.3.0'
  dart_to_js_script_rewriter: '^0.1.0'
  dnd: '>=0.3.0 <0.4.0'
  http: '>=0.11.1 <0.12.0'
  google_charts: '>=0.1.0 <0.2.0'
  uuid: '>=0.5.0 <0.6.0'
  mdl: '^1.0.0'
  di: '^3.3.0'
  js: any
  func: any

transformers:
- dart_to_js_script_rewriter
- di
